# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 992c217416df75b0abb6e12c5a857268465aef7c923a8888614eb1ef9016413ab08ec0e24dab07f5c83fd4ebda75bf2701fb555660094602db18e53a8ca415a2

test:
  secret_key_base: 2f78a3390e0623cb24bdc5da36a13b08a603b0fa67afb7167c2373a382a7cb2265e130607b287af4d3e32058b72f740fdc7714af0f922c9de59b0616933a2e92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
